require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CyclesController do

  # This should return the minimal set of attributes required to create a valid
  # Cycle. As you add validations to Cycle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CyclesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cycles as @cycles" do
      cycle = Cycle.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cycles).should eq([cycle])
    end
  end

  describe "GET show" do
    it "assigns the requested cycle as @cycle" do
      cycle = Cycle.create! valid_attributes
      get :show, {:id => cycle.to_param}, valid_session
      assigns(:cycle).should eq(cycle)
    end
  end

  describe "GET new" do
    it "assigns a new cycle as @cycle" do
      get :new, {}, valid_session
      assigns(:cycle).should be_a_new(Cycle)
    end
  end

  describe "GET edit" do
    it "assigns the requested cycle as @cycle" do
      cycle = Cycle.create! valid_attributes
      get :edit, {:id => cycle.to_param}, valid_session
      assigns(:cycle).should eq(cycle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cycle" do
        expect {
          post :create, {:cycle => valid_attributes}, valid_session
        }.to change(Cycle, :count).by(1)
      end

      it "assigns a newly created cycle as @cycle" do
        post :create, {:cycle => valid_attributes}, valid_session
        assigns(:cycle).should be_a(Cycle)
        assigns(:cycle).should be_persisted
      end

      it "redirects to the created cycle" do
        post :create, {:cycle => valid_attributes}, valid_session
        response.should redirect_to(Cycle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cycle as @cycle" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cycle.any_instance.stub(:save).and_return(false)
        post :create, {:cycle => {}}, valid_session
        assigns(:cycle).should be_a_new(Cycle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cycle.any_instance.stub(:save).and_return(false)
        post :create, {:cycle => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cycle" do
        cycle = Cycle.create! valid_attributes
        # Assuming there are no other cycles in the database, this
        # specifies that the Cycle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cycle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cycle.to_param, :cycle => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cycle as @cycle" do
        cycle = Cycle.create! valid_attributes
        put :update, {:id => cycle.to_param, :cycle => valid_attributes}, valid_session
        assigns(:cycle).should eq(cycle)
      end

      it "redirects to the cycle" do
        cycle = Cycle.create! valid_attributes
        put :update, {:id => cycle.to_param, :cycle => valid_attributes}, valid_session
        response.should redirect_to(cycle)
      end
    end

    describe "with invalid params" do
      it "assigns the cycle as @cycle" do
        cycle = Cycle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cycle.any_instance.stub(:save).and_return(false)
        put :update, {:id => cycle.to_param, :cycle => {}}, valid_session
        assigns(:cycle).should eq(cycle)
      end

      it "re-renders the 'edit' template" do
        cycle = Cycle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cycle.any_instance.stub(:save).and_return(false)
        put :update, {:id => cycle.to_param, :cycle => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cycle" do
      cycle = Cycle.create! valid_attributes
      expect {
        delete :destroy, {:id => cycle.to_param}, valid_session
      }.to change(Cycle, :count).by(-1)
    end

    it "redirects to the cycles list" do
      cycle = Cycle.create! valid_attributes
      delete :destroy, {:id => cycle.to_param}, valid_session
      response.should redirect_to(cycles_url)
    end
  end

end
